# Generated by Django 5.0.4 on 2024-04-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("publishing_datetime", models.DateTimeField()),
                ("thumbnail_url", models.URLField()),
                ("video_id", models.CharField(unique=True)),
            ],
        ),
    ]
